num1=int(input("Enter first number: "))
num2=int(input("Enter Second number: "))
print(f"Addition = {num1+num2}")
print(f"Subtraction = {num1-num2}")
print(f"Multiplication = {num1*num2}")
print(f"Division = {num1/num2}")